version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: password

#  adminer:
#    image: adminer
#    restart: unless-stopped
#    ports:
#      - 127.0.0.1:8880:8080
