version: "3"

services:
  mc:
    image: itzg/minecraft-server
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - ONLINE_MODE=false
      - EULA=TRUE
      - MODE=survival
      - MOTD="HACKED BY XPLOT1ON"
      - LEVEL_TYPE=LARGEBIOMES
      - SPAWN_NPCS=true
      - SPAWN_ANIMALS=true
      - SPAWN_MONSTERS=true
      - GENERATE_STRUCTURES=true
      - FORCE_GAMEMODE=false
      - ENABLE_COMMAND_BLOCK=true
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - ALLOW_NETHER=true
      - SERVER_PORT=25565
      - OPS=XPLOT1ON