version: '3.2'

services:
  minio1:
    image: minio/minio
    container_name: minio
    command: server /data
    ports:
      - 127.0.0.1:9000:9000
#     volumes:
#      - ./data:/data
#      - ./config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
      - MINIO_BROWSER=on
      - MINIO_WORK=on

